title: Trackts App
description: Strive School Build Week Project
logo: /imgs/logo_trackts.png
# show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
theme: jekyll-theme-minimal
