title: Google Fit Project
description: Strive School Build Week Project
logo: /imgs/ntc.jpeg
# show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
theme: jekyll-theme-minimal
